# Generated by Django 5.2.12 on 2026-04-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_status',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlandi', 'Tasdiqlandi'), ('Tayyorlanmoqda', 'Tayyorlanmoqda'), ('Yo‘lga chiqdi', 'Yo‘lga chiqdi'), ('Yetkazildi', 'Yetkazildi'), ('Bekor qilindi', 'Bekor qilindi'), ('Qaytarildi', 'Qaytarildi')], default='Kutilmoqda', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='app.uzumproduct'),
        ),
    ]
