# Generated by Django 5.2.9 on 2026-04-14 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('karta_nomer', models.CharField(max_length=19)),
                ('muddat', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('cart_egasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
