# Generated by Django 5.2.12 on 2026-04-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_carts',
            name='muddat',
            field=models.CharField(max_length=5),
        ),
    ]
