# Generated by Django 5.2.9 on 2026-04-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_carts_muddat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_egasi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_banks_carts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='karta_nomer',
            field=models.CharField(default=1, max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='muddat',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
