# Generated by Django 5.2.9 on 2026-04-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_cart_egasi_order_cvv_order_karta_nomer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_egasi',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='karta_nomer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='muddat',
        ),
    ]
