# Generated by Django 5.2.9 on 2026-04-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_order_cart_egasi_remove_order_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CVV'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Amal qilish muddati'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Karta egasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Karta raqami'),
        ),
    ]
