# Generated by Django 5.2.9 on 2026-04-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_card_cvv_order_card_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_holder_name',
        ),
    ]
