# Generated by Django 5.2.12 on 2026-04-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_users_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='telegram_id',
        ),
    ]
