# Generated by Django 5.2.12 on 2026-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_users_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmark', models.CharField(max_length=255, verbose_name="Mo'ljal (Qayerga yaqin?)")),
                ('full_address', models.CharField(max_length=500, verbose_name="To'liq manzil")),
                ('extra_info', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
            },
        ),
    ]
